# fly.toml app configuration file generated for ai-invesment-mcp-server on 2025-11-20T22:37:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-invesment-mcp-server'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
